const FIREWORKS = "fireworks";
export const LOCATION_HASH = {
	HOME: "home",
	FIREWORKS,
	FIREWORKS_HASH: `#${FIREWORKS}`,
};

export const ANIMATION = {
	FPS: 60,
};

export const SCREEN = {
	MAX_DPR: 3,
	SMALL_WIDTH: 480,
};

export const POS = {
	MAIN_Y_RATIO: 0.15,
};

export const FONT = {
	MAIN_RATIO_GENERAL: 0.09,
	MAIN_RATIO_SMALL: 0.2,
	SUB_RATIO: 0.85,
	FAMILY: "Do Hyeon",
};

export const PARTICLE = {
	RGB: "255, 255, 210",
	HUE: 20,
	MIN_SATURATION: 50,
	MAX_SATURATION: 100,
	MIN_LIGHTNESS: 50,
	MAX_LIGHTNESS: 100,
	MIN_OPACITY: 0.9,
	MAX_OPACITY: 1,
	RADIUS: 1,
	RADIUS_ADJUST_RATIO: 0.8,
	FRICTION: 0.93,
};
